// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedanadditinalcolomntocustomerdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedanadditinalcolomntocustomerdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201909100027250_added-an-additinal-colomn-to-customer-db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
