// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedamodelwherecustomersandemployeesarepairedbasedonthetheday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedamodelwherecustomersandemployeesarepairedbasedonthetheday));
        
        string IMigrationMetadata.Id
        {
            get { return "201912132252422_added a model where customers and employees are paired based on the the day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
