// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deletedbalanceandpickupdatefromemployeemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedbalanceandpickupdatefromemployeemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201909061237004_deleted-balance-and-pickupdate-from-employee-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
